### ISSUE TITLE
Database Service is not ready

### ISSUE THREAD

**Issue by Waffelparty** [Xabis/MALT#2]
I Installed Kodi with MALT on my TV. Installation works fine but If I want to Start the addon it says the database service is not ready. What can I Do?

**Comment by CtrlAltDefeat94** [comment]
A workaround is to delete the files in the addon's appdata directory, and then to reinstall the addon. 
But unfortunately this error seems to occur very frequently, so you'll have to do it very often.

**Comment by Waffelparty** [comment]
I use this plugin on my TV :) So it isnt so easy to Do that but thank you

Am 12.03.2018 21:44 schrieb "CtrlAltDefeat94" <notifications@github.com>:

**Comment by CtrlAltDefeat94** [comment]
I am consistantly able to reproduce this. It appears to happen _every_ time Kodi is restarted.

**Comment by Xabis** [comment]
Looks like the anime relationship database file format changed, which was causing errors. I went ahead and fixed the parsing of it, and released v1.0.2. 

As for the TV aspect, I do not own a smart TV, so cant really test that, sorry.
