### ISSUE TITLE
AniList support

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [Xabis/MALT#6]
With the downfall of the MAL API, would it be possible to support AniList?
Though it would probably require a name change of the project :P

**Comment by Xabis** [comment]
Hopefully the downtime is only temporary. That said, I am unfortunately unable to redo support for another API at this time. If you are on windows, I would recommend using Taiga which can interface with Anilist/Kitsu.

**Comment by CtrlAltDefeat94** [comment]
That's too bad.
Personally I doubt we'll see a new API for MAL for a while(though I don't mind being proven wrong).

I'll be using Taiga for now, but will definitely use your plugin again if you get around supporting AniList

**Comment by Xabis** [comment]
Support is now added in v1.1.0
